### PR TITLE
Automatic astyle + clang 3.5.2 fixes

### PR DESCRIPTION
**Pull request by narc0tiq**
Hey, I just did an astyle on your branch; if you accept the PR here, it'll be added to CleverRaven/Cataclysm-DDA#25262.

While I'm here, I'll take a look at the other compile error I was having, so maybe give me a few minutes before you merge?

### CODE REVIEW

**Comment by narc0tiq** [comment]
Hmm... this is very strange, I'm getting:
```
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra  -g  -fsigned-char -Werror -std=c++11 -MMD -MP -m32 -I/usr/include/lua5.2 -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/calendar.cpp -o obj/calendar.o
src/calendar.cpp:319:26: error: use of undeclared identifier 'to_weeks'
        const int week = to_weeks<int>( d );
                         ^
src/calendar.cpp:319:38: error: expected '(' for function-style cast or type construction
        const int week = to_weeks<int>( d );
                                  ~~~^
2 errors generated.
Makefile:787: recipe for target 'obj/calendar.o' failed
make: *** [obj/calendar.o] Error 1
make: *** Waiting for unfinished jobs....
zsh: exit 2     DEBUG_SYMBOLS=yes Platform=Linux Graphics=Curses
DEBUG_SYMBOLS=yes Platform=Linux Graphics=Curses   15.81s user 1.03s system 122% cpu 13.712 total
```

...but `to_weeks` is declared in `calendar.h`, right where `to_days` is (and that one works just fine). Any idea wtf? I'm not really a C++ person, and this feels like a C++ oddity.

**Comment by narc0tiq** [comment]
Nevermind, I get what happened there -- `to_weeks` is declared inside the `time_duration` class, but it's being used unqualified; by comparison, `to_days` also exists as a `constexpr` defined in the global namespace, which is probably what allows it to be used bare like it is a few lines before the error in `calendar.cpp`

**Comment by MT-Arnoldussen** [comment]
Well, I made the to_weeks stuff, so I guess I might have forgotten something? I'm not super familiar with C++. 

In all of my testing it seems to work just fine though.

**Comment by narc0tiq** [comment]
It's strange that your compiler is letting you get away with that; `clang++` here refuses to let me play unless I fix it. Happily, the fix I just mentioned does actually work, so I'll just add that along into this PR once the compile finishes.

**Comment by MT-Arnoldussen** [comment]
Alright, thanks for catching that.

**Comment by narc0tiq** [comment]
Mm, more issues:
```
CCACHE_CPP2=1 ccache clang++  -DRELEASE -DGIT_VERSION -DLOCALIZE -ffast-math -Os  -Wall -Wextra  -g  -fsigned-char -Werror -std=c++11 -MMD -MP -m32 -I/usr/include/lua5.2 -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/game_inventory.cpp -o obj/game_inventory.o
src/game_inventory.cpp:400:17: error: return type 'basic_string<[...]>' must match previous return type 'const basic_string<[...]>' when lambda expression has unspecified explicit return type
                return std::string();
                ^
src/game_inventory.cpp:414:17: error: return type 'basic_string<[...]>' must match previous return type 'const basic_string<[...]>' when lambda expression has unspecified explicit return type
                return std::string();
                ^
src/game_inventory.cpp:526:41: error: unused variable 'time_left' [-Werror,-Wunused-variable]
                    const time_duration time_left = time_duration::from_hours( 6 );
                                        ^
src/game_inventory.cpp:529:37: error: unused variable 'time_left' [-Werror,-Wunused-variable]
                const time_duration time_left = time_duration::from_days( ceilf( days_left ) );
                                    ^
src/game_inventory.cpp:531:37: error: unused variable 'time_left' [-Werror,-Wunused-variable]
                const time_duration time_left = time_duration::from_days( ceilf( days_left / 7 ) * 7 );
                                    ^
src/game_inventory.cpp:534:37: error: unused variable 'time_left' [-Werror,-Wunused-variable]
                const time_duration time_left = get_edible_comestible( loc ).spoils;
                                    ^
src/game_inventory.cpp:520:23: error: unused variable 'skill' [-Werror,-Wunused-variable]
            const int skill = p.get_skill_level( skill_survival );
                      ^
7 errors generated.
Makefile:787: recipe for target 'obj/game_inventory.o' failed
make: *** [obj/game_inventory.o] Error 1
```

I'll keep plugging away at these, I guess. At least unused variables are easy to deal with.

**Comment by MT-Arnoldussen** [comment]
Right I was wondering if using `const` like that was okay, but it didn't let me assign `time_duration` variables without `const`.

I guess Visual Studio accepts all kinds of stuff clang++ doesn't.

edit: tested it again and it works fine. was probably something else that gave an error

**Comment by narc0tiq** [comment]
Ok, what's happening on lines 526 and friends (`const time_duration time_left = ...`) is that you're creating new variables inside the if/else scope that are never used. What you probably wanted was to make the outer `time_left` non-const (because we're going to mutate it).

Haven't looked at the other problems yet.

**Comment by narc0tiq** [comment]
Ok, so that leaves the `return type 'basic_string<[...]>' must match previous return type 'const basic_string<[...]>' when lambda expression has unspecified explicit return type`, which is very odd to me because lines 400 and 414 look the same to me as the working one at line 388.

There must be something I'm not seeing.

**Comment by narc0tiq** [comment]
Got it -- the compiler got confused because it found the first return is of a `const`, and assumed the whole lambda must be returning a const. If we just remove the `const` and leave them as ordinary `std::string freshness` and such, it compiles.

Entertainingly, the `get_freshness` function is labeled as returning a `const`, so you can't return it directly -- you must pass it through the non-const variable declaration.

**Comment by MT-Arnoldussen** [comment]
Alright. Let me know when/if you're ready for this to get merged.

**Comment by narc0tiq** [comment]
Here we go; I squashed the extra commits (the three you've seen and a fourth one) into a single set of fixes for clang compilation.

At this point, the head of this branch compiles on my machine, so it's good to merge. You'll have to test to make sure it still does what it's supposed to, of course.

**Comment by MT-Arnoldussen** [comment]
Well my own PR isn't entirely done yet, so if there's still issues after merging your commits that wouldn't be a problem.

**Pull request merged**
